namespace ThesisApi.Models
{
    public enum EventType
    {
        Login,
        GetUsers,
        GetUser,
        CreateUser,
        DeleteUser,
        GetComputers,
        GetComputer,
        CreateComputer,
        DeleteComputer,
        GetComputerOrders,
        GetComputerOrder,
        CreateComputerOrder,
        DeleteComputerOrder,
        GetMobileDevices,
        GetMobileDevice,
        CreateMobileDevice,
        DeleteMobileDevice,
        GetMobileOrders,
        GetMobileOrder,
        CreateMobileOrder,
        DeleteMobileOrder,
        GetSimCards,
        GetSimCard,
        CreateSimCard,
        DeleteSimCard
    }
}