// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThesisApi.Data;

#nullable disable

namespace ThesisApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251012124130_RemoveDepartmentFromSimCards")]
    partial class RemoveDepartmentFromSimCards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThesisApi.Models.MobileDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImeiNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MobileDeviceCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SimCardId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MobileDeviceCategoryId");

                    b.HasIndex("SimCardId")
                        .IsUnique()
                        .HasFilter("[SimCardId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("MobileDevices");
                });

            modelBuilder.Entity("ThesisApi.Models.MobileDeviceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MobileDeviceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Standard smartphone"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Enhanced smartphone"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Feature phone"
                        });
                });

            modelBuilder.Entity("ThesisApi.Models.MobileOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("MobileDeviceCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("MobileDeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SimCallControlGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("SimCardId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MobileDeviceCategoryId");

                    b.HasIndex("MobileDeviceId");

                    b.HasIndex("SimCallControlGroupId");

                    b.HasIndex("SimCardId");

                    b.ToTable("MobileOrders");
                });

            modelBuilder.Entity("ThesisApi.Models.SimCallControlGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDataEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SimCallControlGroups");
                });

            modelBuilder.Entity("ThesisApi.Models.SimCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SimCallControlGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SimCallControlGroupId");

                    b.ToTable("SimCards");
                });

            modelBuilder.Entity("ThesisApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CostCenter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ThesisApi.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("UserUserRole", b =>
                {
                    b.Property<int>("UserRolesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("UserRolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserUserRole");
                });

            modelBuilder.Entity("ThesisApi.Models.MobileDevice", b =>
                {
                    b.HasOne("ThesisApi.Models.MobileDeviceCategory", "MobileDeviceCategory")
                        .WithMany("MobileDevices")
                        .HasForeignKey("MobileDeviceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThesisApi.Models.SimCard", "SimCard")
                        .WithOne("MobileDevice")
                        .HasForeignKey("ThesisApi.Models.MobileDevice", "SimCardId");

                    b.HasOne("ThesisApi.Models.User", "User")
                        .WithMany("MobileDevices")
                        .HasForeignKey("UserId");

                    b.Navigation("MobileDeviceCategory");

                    b.Navigation("SimCard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThesisApi.Models.MobileOrder", b =>
                {
                    b.HasOne("ThesisApi.Models.User", "Customer")
                        .WithMany("MobileOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThesisApi.Models.MobileDeviceCategory", "MobileDeviceCategory")
                        .WithMany("MobileOrders")
                        .HasForeignKey("MobileDeviceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThesisApi.Models.MobileDevice", "MobileDevice")
                        .WithMany("MobileOrders")
                        .HasForeignKey("MobileDeviceId");

                    b.HasOne("ThesisApi.Models.SimCallControlGroup", "SimCallControlGroup")
                        .WithMany("MobileOrders")
                        .HasForeignKey("SimCallControlGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThesisApi.Models.SimCard", "SimCard")
                        .WithMany("MobileOrders")
                        .HasForeignKey("SimCardId");

                    b.Navigation("Customer");

                    b.Navigation("MobileDevice");

                    b.Navigation("MobileDeviceCategory");

                    b.Navigation("SimCallControlGroup");

                    b.Navigation("SimCard");
                });

            modelBuilder.Entity("ThesisApi.Models.SimCard", b =>
                {
                    b.HasOne("ThesisApi.Models.SimCallControlGroup", "SimCallControlGroup")
                        .WithMany("SimCards")
                        .HasForeignKey("SimCallControlGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimCallControlGroup");
                });

            modelBuilder.Entity("UserUserRole", b =>
                {
                    b.HasOne("ThesisApi.Models.UserRole", null)
                        .WithMany()
                        .HasForeignKey("UserRolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThesisApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ThesisApi.Models.MobileDevice", b =>
                {
                    b.Navigation("MobileOrders");
                });

            modelBuilder.Entity("ThesisApi.Models.MobileDeviceCategory", b =>
                {
                    b.Navigation("MobileDevices");

                    b.Navigation("MobileOrders");
                });

            modelBuilder.Entity("ThesisApi.Models.SimCallControlGroup", b =>
                {
                    b.Navigation("MobileOrders");

                    b.Navigation("SimCards");
                });

            modelBuilder.Entity("ThesisApi.Models.SimCard", b =>
                {
                    b.Navigation("MobileDevice");

                    b.Navigation("MobileOrders");
                });

            modelBuilder.Entity("ThesisApi.Models.User", b =>
                {
                    b.Navigation("MobileDevices");

                    b.Navigation("MobileOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
